name: PNPM Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment variables
        run: |
          echo "ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_NFT_MARKETPLACE_SMART_CONTRACT_ADDRESS=${{ secrets.NEXT_PUBLIC_NFT_MARKETPLACE_SMART_CONTRACT_ADDRESS }}" >> $GITHUB_ENV

      - name: Print env variables
        run: env

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.6.1
          cache: 'pnpm'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build
