name: To delete

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Test
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          xvfb-run --auto-servernum pnpm exec playwright test --headed --timeout 60000
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results
