name: E2E Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4

      - name: Checkout hardhat-smart-contract
        uses: actions/checkout@v4
        with:
          repository: pleszko​​wicz/hardhat-smart-contract
          path: hardhat-smart-contract

      - name: Install contracts deps & build
        run: |
          cd hardhat-smart-contract
          npm ci
          npx hardhat compile

      - name: Start Hardhat Node
        run: |
          cd hardhat-smart-contract
          npx hardhat node --hostname 0.0.0.0 --port 8545 &
      - name: Wait for Hardhat RPC
        run: npx wait-on http://localhost:8545

      - name: Install frontend deps
        run: npm install -g pnpm && pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Copy ABI to frontend
        run: |
          mkdir -p lib/abi
          cp hardhat-smart-contract/artifacts/contracts/*.json lib/abi/

      - name: Build frontend
        run: pnpm run build

      - name: Start frontend
        run: npm run start &

      - name: Wait for frontend
        run: npx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: pnpm exec playwright test
        env:
          CI: true

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
