name: E2E Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      hardhat:
        image: node:20.6.1
        options: >-
          --entrypoint "/bin/bash -c 'cd /contracts && npm ci && npx hardhat node'"
          --health-cmd "curl --fail http://localhost:8545 || exit 1"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 10
        ports:
          - 8545:8545
        volumes:
          - ../my-contracts:/contracts

    steps:
      - uses: actions/checkout@v4

      - name: Checkout contracts repo
        uses: actions/checkout@v4
        with:
          repository: pleszkowicz/hardhat-smart-contract
          path: my-contracts

      - name: Install contracts deps & build
        run: |
          cd my-contracts
          npm ci
          npx hardhat compile

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Copy ABI to frontend
        run: |
          mkdir -p lib/abi
          cp my-contracts/artifacts/contracts/*.json lib/abi/

      - name: Build frontend
        run: pnpm run build

      - name: Start frontend
        run: npm run start &

      - name: Wait for frontend
        run: npx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: pnpm exec playwright test
        env:
          CI: true

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
