name: E2E Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.6.1

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.0

      - name: Get pnpm store directory
        shell: bash
        run: |
          STORE_PATH=$(pnpm store path 2>/dev/null || echo "/tmp/.pnpm-store")
          echo "STORE_PATH=$STORE_PATH" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Cache MetaMask extension (dappwright)
        uses: actions/cache@v4
        with:
          # The path must match the `downloadDir` in tests/metamaskSetup.ts
          path: ./.cache/metamask
          key: ${{ runner.os }}-metamask-v12.16.0
          restore-keys: |
            ${{ runner.os }}-metamask-

      - name: Checkout hardhat-nft-marketplace
        uses: actions/checkout@v4
        with:
          repository: pleszkowicz/hardhat-nft-marketplace
          path: smart-contract

      - name: Install contracts deps
        run: |
          cd smart-contract
          npm ci

      - name: Start Hardhat Node
        run: |
          cd smart-contract
          npx hardhat node --hostname 0.0.0.0 --port 8545 &
      - name: Wait for Hardhat RPC
        run: npx wait-on http://localhost:8545

      - name: Debug List NftMarketplace.ts files
        run: find smart-contract -iname "NftMarketplace.ts"

      - name: Deploy contracts to local node
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
        run: |
          cd smart-contract
          npm run deploy:local > deploy-output.txt

      - name: Show deploy-output.txt
        run: cat smart-contract/deploy-output.txt

      - name: Extract contract address
        run: |
          mkdir -p lib/abi
          ADDRESS=$(grep -oE '0x[a-fA-F0-9]{40}' smart-contract/deploy-output.txt | head -1)
          echo "{\"NftMarketplace\":\"$ADDRESS\"}" > lib/abi/contract-address.json
          echo "NEXT_PUBLIC_CUSTOM_NFT_MARKETPLACE_SMART_CONTRACT_ADDRESS=$ADDRESS" >> $GITHUB_ENV

      - name: Copy ABI to frontend
        run: |
          mkdir -p lib/abi
          cp smart-contract/artifacts/contracts/*/*.json lib/abi/

      - name: Create .env.local with dynamic address
        run: |
          echo "NEXT_PUBLIC_CUSTOM_NFT_MARKETPLACE_SMART_CONTRACT_ADDRESS=$ADDRESS" > .env.local

      - name: Install frontend deps
        run: pnpm i

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Run build
        env:
          NEXT_PUBLIC_CUSTOM_NFT_MARKETPLACE_SMART_CONTRACT_ADDRESS: ${{ env.NEXT_PUBLIC_CUSTOM_NFT_MARKETPLACE_SMART_CONTRACT_ADDRESS }}
          NEXT_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm build

      # - name: Start frontend
      #   run: npm run start &
      #   env:
      #     NEXT_PUBLIC_CUSTOM_NFT_MARKETPLACE_SMART_CONTRACT_ADDRESS: ${{ env.NEXT_PUBLIC_CUSTOM_NFT_MARKETPLACE_SMART_CONTRACT_ADDRESS }}
      #     NEXT_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_API_KEY }}
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # - name: Wait for frontend
      #   run: npx wait-on http://localhost:3000

      - name: Debug cache directory before tests
        run: |
          echo "Content of ./.cache:"
          ls -R ./.cache || echo "No .cache directory found"

      - name: Run Playwright tests
        run: xvfb-run --auto-servernum -- pnpm exec playwright test
        env:
          CI: true
          NEXT_PUBLIC_CUSTOM_NFT_MARKETPLACE_SMART_CONTRACT_ADDRESS: ${{ env.NEXT_PUBLIC_CUSTOM_NFT_MARKETPLACE_SMART_CONTRACT_ADDRESS }}
          NEXT_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
